version: "3.4"
services:
  keytool:
    image: besugi/eth2-val-tools:latest
    container_name: keytool
    volumes:
      - ./secrets:/validator_data
    command: >
      keystores
      --insecure
      --prysm-pass="prysm"
      --out-loc="/validator_data/keys"
      --source-max=${VALIDATOR_INDEX_MAX}
      --source-min=${VALIDATOR_INDEX_MIN}
      --source-mnemonic="${VALIDATORS_MNEMONIC}"
  besu:
    image: hyperledger/besu:22.1.4-SNAPSHOT
    container_name: besu
    volumes:
      - ./execution_data:/execution_data
      - ./config:/config
    command: >
      --network=kiln
      --data-path="/execution_data"
      --rpc-http-enabled=true
      --rpc-ws-enabled=true
      --host-allowlist="*"
      --rpc-http-cors-origins="*"
      --rpc-http-api=ADMIN,ETH,NET,DEBUG,TXPOOL
      --p2p-enabled=true
      --Xmerge-support=true
      --data-storage-format="BONSAI"
      --engine-host-allowlist="*"
      --miner-enabled=true
      --rpc-http-host=0.0.0.0
      --rpc-ws-host=0.0.0.0
      --p2p-host=$IP_ADDRESS
      --miner-coinbase="${COINBASE}"
    network_mode: host
  lodestar-bn:
    image: chainsafe/lodestar:next
    container_name: lodestar-bn
    depends_on: 
      - besu
      - keytool
    volumes:
      - ./lodestar_data:/consensus_data
      - ./config:/config
    command: >
      beacon --rootDir=/consensus_data --paramsFile=/config/config.yaml
      --genesisStateFile=/config/genesis.ssz --network.discv5.bootEnrs=$ENR
      --network.connectToDiscv5Bootnodes --network.discv5.enabled=true --eth1.enabled=true
      --api.rest.port=4000 --eth1.disableEth1DepositDataTracker=true
      --eth1.providerUrls=http://127.0.0.1:8545 --execution.urls=http://127.0.0.1:8550
      --api.rest.enabled=true --api.rest.host=0.0.0.0 --api.rest.api="*" --enr.ip=$IP_ADDRESS
      --eth1.depositContractDeployBlock=0
    network_mode: host
  lodestar-vc:
    image: chainsafe/lodestar:next
    container_name: lodestar-vc
    depends_on: 
      - lodestar-bn
    volumes:
      - ./lodestar_data:/consensus_data
      - ./config:/config
      - ./secrets/keys:/secrets
    command: >
      validator
       --rootDir=/consensus_data
       --paramsFile=/config/config.yaml
       --keystoresDir=/secrets/keys
       --secretsDir=/secrets/lodestar-secrets
       --server=http://127.0.0.1:4000
       --logFile=/validatordata/validator.log
       --logLevelFile=debug
       --logRotate
       --logMaxFiles=5
       --graffiti="besugi-lodestar"
    network_mode: host
