version: "3.4"
services:
  eth2_val_tools:
    image: suburbandad/eth2-val-tools:latest
    container_name: keytool
    volumes:
      - ./nimbus_data:/validator_data
    command: >
      keystores
      --insecure
      --prysm-pass="prysm"
      --out-loc="/validator_data/keys"
      --source-max=${VALIDATOR_INDEX_MAX}
      --source-min=${VALIDATOR_INDEX_MIN}
      --source-mnemonic="${VALIDATOR_MNEMONIC}"
  besu:
    image: suburbandad/besu:kintsugi-v3
    container_name: besu
    volumes:
      - ./execution_data:/execution_data
      - ./config:/config
    command: >
      --data-path="/execution_data"
      --genesis-file="/config/besu_genesis.json"
      --network-id=$NETWORK_ID
      --rpc-http-enabled=true
      --rpc-ws-enabled=true
      --rpc-http-api=ADMIN,CLIQUE,MINER,ETH,NET,DEBUG,TXPOOL,EXECUTION
      --rpc-ws-api=ADMIN,CLIQUE,MINER,ETH,NET,DEBUG,TXPOOL,EXECUTION
      --host-allowlist="*"
      --rpc-http-cors-origins="*"
      --p2p-enabled=true
      --Xmerge-support=true
      --Xdata-storage-format="BONSAI"
      --miner-enabled=true
      --rpc-http-host=0.0.0.0
      --rpc-ws-host=0.0.0.0
      --p2p-host=$IP_ADDRESS
      --bootnodes=$ENODE
      --miner-coinbase="${COINBASE}"
    network_mode: host
  nimbus:
    image: parithoshj/nimbus:merge-d5c48e1
    container_name: nimbus
    volumes:
      - ./nimbus_data:/consensus_data
      - ./config:/config
    command: >
      beacon_node --non-interactive=true --network="/config"
      --data-dir="/consensus_data" --web3-url=ws://127.0.0.1:8546
      --bootstrap-node=$ENR --nat="extip:$IP_ADDRESS" --enr-auto-update=false
      --rest --rest-port=4000
      --terminal-total-difficulty-override=$TOTAL_TERMINAL_DIFFICULTY
    network_mode: host