version: "3.4"
services:
  keytool:
    image: besugi/eth2-val-tools:latest
    container_name: keytool
    volumes:
      - ./secrets:/validator_data
    command: >
      keystores
      --insecure
      --prysm-pass="prysm"
      --out-loc="/validator_data/keys"
      --source-max=${VALIDATOR_INDEX_MAX}
      --source-min=${VALIDATOR_INDEX_MIN}
      --source-mnemonic="${VALIDATORS_MNEMONIC}"
  besu:
    image: hyperledger/besu:22.1.3-SNAPSHOT
    container_name: besu
    user: root
    volumes:
      - ./execution_data:/execution_data
      - ./config:/config
    command: >
      --genesis-file="/config/besu_genesis.json"
      --network-id=$NETWORK_ID
      --sync-mode="FAST"
      --data-path="/execution_data"
      --rpc-http-enabled=true
      --rpc-ws-enabled=true
      --host-allowlist="*"
      --rpc-http-cors-origins="*"
      --p2p-enabled=true
      --Xmerge-support=true
      --data-storage-format="BONSAI"
      --engine-host-allowlist="*"
      --miner-enabled=true
      --rpc-http-host=0.0.0.0
      --rpc-ws-host=0.0.0.0
      --p2p-host=$IP_ADDRESS
      --bootnodes=$ENODE
      --miner-coinbase="${COINBASE}"
    network_mode: host
  teku:
    image: consensys/teku:latest
    container_name: teku
    depends_on: 
      - besu
      - keytool
    volumes:
      - ./teku_data:/consensus_data
      - ./secrets/keys/teku-keys:/keys
      - ./secrets/keys/teku-secrets:/secrets
      - ./config:/config
    command: >
      --network "/config/config.yaml"
      --initial-state "/config/genesis.ssz"
      --data-path "/consensus_data" --data-storage-mode=PRUNE
      --p2p-enabled=true --eth1-endpoints=http://127.0.0.1:8545
      --ee-endpoint=http://127.0.0.1:8550
      --p2p-advertised-ip=$IP_ADDRESS --p2p-discovery-bootnodes=$ENR
      --rest-api-enabled=true --rest-api-docs-enabled=true
      --rest-api-interface=0.0.0.0 --rest-api-port=4000
      --rest-api-host-allowlist=* --data-storage-non-canonical-blocks-enabled=true
      --network-merge-total-terminal-difficulty-override=$TOTAL_TERMINAL_DIFFICULTY
      --validators-proposer-default-fee-recipient="${COINBASE}"
      --validator-keys=/keys:/secrets
      --log-destination=CONSOLE
      --ee-version=kilnv2
      --validators-graffiti="besugi-teku"
      --validators-keystore-locking-enabled=false
    network_mode: host
