version: "3.4"
services:
  keytool:
    image: besugi/eth2-val-tools:latest
    container_name: keytool
    volumes:
      - ./secrets:/validator_data
    command: >
      keystores
      --insecure
      --prysm-pass="prysm"
      --out-loc="/validator_data/keys"
      --source-max=${VALIDATOR_INDEX_MAX}
      --source-min=${VALIDATOR_INDEX_MIN}
      --source-mnemonic="${VALIDATORS_MNEMONIC}"
  besu:
    image: hyperledger/besu:22.1.3-SNAPSHOT
    container_name: besu
    user: root
    volumes:
      - ./execution_data:/execution_data
      - ./config:/config
    command: >
      --network=kiln
      --data-path="/execution_data"
      --rpc-http-enabled=true
      --rpc-ws-enabled=true
      --host-allowlist="*"
      --rpc-http-cors-origins="*"
      --rpc-http-api=ADMIN,ETH,NET,DEBUG,TXPOOL
      --p2p-enabled=true
      --Xmerge-support=true
      --data-storage-format="BONSAI"
      --engine-host-allowlist="*"
      --miner-enabled=true
      --rpc-http-host=0.0.0.0
      --rpc-ws-host=0.0.0.0
      --p2p-host=$IP_ADDRESS
      --bootnodes=$ENODE
      --miner-coinbase="${COINBASE}"
    network_mode: host
  prysm:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:kiln-b9ffd6
    container_name: prysm
    depends_on: 
      - besu
      - keytool
    volumes:
      - ./prysm_data:/prysm_data
      - ./secrets/keys/prysm-keys:/keys
      - ./secrets/keys/prysm:/secrets
      - ./config:/config
    command: >
      --accept-terms-of-use
      --genesis-state /config/genesis.ssz 
      --datadir /prysm_data 
      --http-web3provider=http://localhost:8550 
      --min-sync-peers=1 
      --chain-config-file /config/config.yaml 
      --bootstrap-node "${ENR}" 
      --suggested-fee-recipient "${COINBASE}"
    network_mode: host
